name: highlight_text
description: With this package you can highlight words and create specific styles and actions.
version: 1.6.0
homepage: https://github.com/desconexo/highlight_text

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
